#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $API_DB_USER WITH PASSWORD '$API_DB_PASSWORD';
	CREATE DATABASE $API_DB_DATABASE;
	GRANT ALL PRIVILEGES ON DATABASE $API_DB_DATABASE TO $API_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$API_DB_DATABASE" <<-EOSQL
	GRANT ALL ON SCHEMA public TO $API_DB_USER;
EOSQL