version: '3'

services:
  api:
    image: longtemps_api:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "6900:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: longtemps
      DB_PASSWORD: longtemps-pwd
      DB_DATABASE: longtemps
      AUTH_ISSUER: https://auth.zigoulero.net/realms/longtemps
      AUTH_CLIENT_ID: longtemps-api
      AUTH_CLIENT_SECRET: LV9livocckzvfe4xhMRntVfQPNW01bQS
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 6901:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: longtemps
      POSTGRES_PASSWORD: longtemps-pwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U longtemps" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/postgresql:/var/lib/postgresql/data:rw

volumes:
  dependencies:
